title: Hi, I'm Darren Pearson
description: > # this means to ignore newlines until "baseurl:"
  Instructor at Saint Paul College, focusing on Graphics, Animation and Web Design. 
  Recently, I've been creating retro games with Javascript and Tumult Hype
permalink: ':title/'
baseurl: "/spcgames.github.io" # the subpath of your site, e.g. /blog
url: "https://spcgames.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Darren Pearson # add your name
author-img: headshot-darren.jpg # add your photo
about-author: I'm a community college instructor who creates retro games in Javascript and Tumult Hype # add description
social-twitter: dpearson100 # add your Twitter handle
social-facebook: dpearson100 # add your Facebook handle
social-github: dpearson100 # add your Github handle
social-linkedin: darrenpearson # add your Linkedin handle
social-email: dpearson100@gmail.com # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
